// Measures every image in a folder and writes the sizes out, for code that looks them up at build time.
import fs from 'node:fs';
import { imageSize } from './dimensions.js';
import { posixRelative, walk } from './files.js';

const IMAGE = /\.(png|jpe?g|gif|webp|avif|svg)$/i;

/** { '/path/to/image.webp': [width, height] } for every readable image under `dir`, sorted by path. */
export function measure(dir, { prefix = '/' } = {}) {
  const base = prefix.endsWith('/') ? prefix : `${prefix}/`;
  const sizes = {};
  const unreadable = [];
  for (const file of walk(dir).filter((f) => IMAGE.test(f)).sort()) {
    const size = imageSize(fs.readFileSync(file));
    const key = base + posixRelative(dir, file);
    if (size) sizes[key] = [Math.round(size.width), Math.round(size.height)];
    else unreadable.push(key);
  }
  return { sizes, unreadable };
}

/** The sizes as JSON, a JavaScript module, or a TypeScript module. */
export function render(sizes, format = 'json') {
  const body = Object.entries(sizes)
    .map(([key, [w, h]]) => `  ${JSON.stringify(key)}: [${w}, ${h}],`)
    .join('\n');
  if (format === 'json') {
    return `{\n${body.replace(/,$/, '')}\n}\n`;
  }
  const type = format === 'ts' ? ': Record<string, [number, number]>' : '';
  return `// Generated by image-dimensions-checker. Run it again when images change.\nexport const IMAGE_SIZES${type} = {\n${body}\n};\n`;
}
